app.py
from flask import Flask
import sqlite3 as sl


def _db_init():
    with open('static/init.sql', 'r') as sql_file:
        sql_script = sql_file.read()

    connection = get_db_connection()

    cursor = connection.cursor()
    print('Executing init script: \n' + sql_script)
    cursor.executescript(sql_script)
    connection.commit()
    connection.close()


def _dict_factory(dict_cursor, row):
    d = {}
    for idx, col in enumerate(dict_cursor.description):
        d[col[0]] = row[idx]
    return d


def get_db_connection():
    connection = sl.connect('database.db')
    connection.row_factory = _dict_factory
    return connection


def create_app():
    app = Flask(__name__)

    app.secret_key = 'your secret key'

    app.config['MYSQL_HOST'] = 'localhost'
    app.config['MYSQL_USER'] = 'root'
    app.config['MYSQL_PASSWORD'] = 'root'
    app.config['MYSQL_DB'] = 'mywebsite'

    _db_init()

    from views.home import bp as bp_home
    from views.about import bp as bp_about
    from views.login import bp as bp_login
    from views.logout import bp as bp_logout
    from views.register import bp as bp_register

    app.register_blueprint(bp_home)
    app.register_blueprint(bp_about)
    app.register_blueprint(bp_login)
    app.register_blueprint(bp_logout)
    app.register_blueprint(bp_register)

    return app


if __name__ == '__main__':
    create_app()

views/about.py
from flask import Blueprint, render_template, session
from app import get_db_connection

bp = Blueprint('about', __name__)


def fetch_user_posts(author_id):
    posts = None
    connection = get_db_connection()
    with connection:
        cursor = connection.cursor()
        query = 'SELECT * FROM posts WHERE author_id='+str(author_id)+';'
        cursor.execute(query)
        posts = cursor.fetchall()
    return posts


@bp.route('/about')
def about():
    if session.get('logged_in'):
        user = session.get('username')
        posts = fetch_user_posts(session.get('id'))
        return render_template("about.html", title="About", user=user, posts=posts)
    else:
        return render_template("about.html", title="About")

views/home.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from app import get_db_connection

bp = Blueprint('home', __name__)


def fetch_posts():
    posts = None
    connection = get_db_connection()
    with connection:
        cursor = connection.cursor()
        cursor.execute('SELECT * FROM posts;')
        posts = cursor.fetchall()
    if session.get('logged_in'):
        author_id = session['id']
        for post in posts:
            if post['author_id'] == author_id:
                post['author'] = 'You'
    return posts


def add_post(title, content):
    if session.get('username') and session.get('id'):
        if title and content:
            username = session.get('username')
            author_id = session.get('id')
            connection = get_db_connection()
            with connection:
                connection.execute("INSERT INTO posts(author_id, author, title, content) VALUES (?, ?, ?, ?)",
                                   (author_id, username, title, content))
    else:
        raise Exception('Not logged in')


def delete_post(post_id):
    if session.get('logged_in') and session.get('username') and session.get('id'):
        user_id = session.get('id')
        user_role = session.get('user_role')
        connection = get_db_connection()
        with connection:
            if user_role == 'ADMIN':
                connection.execute("DELETE FROM posts WHERE id = ?", (post_id, ))
            else:
                connection.execute("DELETE FROM posts WHERE id = ? AND author_id = ?", (post_id, user_id))
    else:
        raise Exception('Failed to delete row')


@bp.route('/')
@bp.route('/home', methods=['GET', 'POST'])
def home():
    user = ''
    if session.get('logged_in'):
        user = session.get('username')

    if request.method == 'POST' and 'post_content' in request.form and 'post_title' in request.form:
        add_post(request.form['post_title'], request.form['post_content'])
    return render_template('home.html', posts=fetch_posts(), user=user)


@bp.route('/home/delete/<post_id>')
def delete(post_id):
    delete_post(post_id)
    return redirect(url_for('home.home'))

views/login.py
import bcrypt
from flask import Blueprint
from flask import render_template, request, session, redirect, url_for

from app import get_db_connection

bp = Blueprint('login', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']

        user = ''
        if session.get('logged_in'):
            user = session.get('username')

        connection = get_db_connection()
        with connection:
            cursor = connection.cursor()
            cursor.execute('SELECT * FROM users WHERE username = ?;', (username,))
            account = cursor.fetchone()
            if account and bcrypt.checkpw(password.encode('utf-8'), account['password'].encode('utf-8')):
                session['logged_in'] = True
                session['id'] = account['id']
                session['username'] = account['username']
                session['user_role'] = account['role']
                return redirect(url_for('home.home', user=user))
            else:
                msg = 'Incorrect username / password !'
                return render_template('login.html', msg=msg, title="Sign In", user=user)
    else:
        return render_template('login.html')

views/logout.py
from flask import Blueprint, redirect, url_for
from flask import session

bp = Blueprint('logout', __name__)


@bp.route('/logout')
def logout():
    session.pop('logged_in', None)
    session.pop('id', None)
    session.pop('username', None)
    session.pop('user_role', None)
    return redirect(url_for('home.home'))

views/register.py
import re

import bcrypt
from flask import Blueprint, session
from flask import render_template, request
from app import get_db_connection


bp = Blueprint('register', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'email' in request.form:
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']

        connection = get_db_connection()
        with connection:
            cursor = connection.cursor()
            cursor.execute('SELECT * FROM users WHERE username = ?;', (username,))
            account = cursor.fetchone()
            if account:
                msg = 'Account already exists !'
            elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
                msg = 'Invalid email address !'
            elif not re.match(r'[A-Za-z0-9]+', username):
                msg = 'Username must contain only characters and numbers !'
            elif not username or not password or not email:
                msg = 'Please fill out the form !'
            else:
                pwd_salt = bcrypt.gensalt()
                pwd_hash = bcrypt.hashpw(password.encode('utf-8'), pwd_salt).decode('utf-8')
                sql = f"INSERT INTO users (username, password, email, role) VALUES ('{username}', '{pwd_hash}', '{email}', 'USER');"
                cursor.execute(sql)
                connection.commit()
                msg = 'You have successfully registered !'
    elif request.method == 'POST':
        msg = 'Please fill out the form !'

    user = ''
    if session.get('logged_in'):
        user = session.get('username')
    return render_template('register.html', msg=msg, title="Sign Up", user=user)

templates/about.html
{%  extends "layout.html" %}
{% block content %}
    <div class="content-section col-md-8 ">
        {% if user %}
            <h3>Hi {{ user }}!</h3>
            {% if posts %}
                <h6>Your posts:</h6>
                {%  for post in posts %}
                    <article class="media content-section">
                      <div class="media-body">
                        <div class="article-metadata">
                          <a class="mr-2" href="#">{{ post.author }}</a>
                        </div>
                        <h2><a class="article-title">{{ post.title }}</a></h2>
                        <p class="article-content">{{ post.content }}</p>
                      </div>
                    {% if session['logged_in'] and post['author_id'] == session['id'] %}
                        <a href="/home/delete/{{ post['id'] }}">
                            <button class="delete-post-button" name="delete_post_button" type="submit">Delete</button>
                        </a>
                    {% endif %}
                    </article>
                {% endfor %}
            {% else %}
                <h6>You have no posts yet</h6>
            {%  endif %}
        {% else %}
            <h3>You're not logged in!</h3>
            <div class="border-top pt-3 col-md-8">
                <small class="text-muted">
                    <a class="ml-2" href="{{ url_for('register.register') }}">Sign In here</a>
                </small>
            </div>
        {%  endif %}

    </div>
{% endblock content%}

templates/home.html
{%  extends "layout.html" %}
{% block content %}
    <div class="row">
    <div class="col-md-8">
        {%  for post in posts %}
            <article class="media content-section">
              <div class="media-body">
                <div class="article-metadata">
                  <a class="mr-2" href="#">{{ post.author }}</a>
                </div>
                <h2><a class="article-title">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
              </div>
            {% if (session['logged_in'] and post['author_id'] == session['id']) or session['user_role'] == 'ADMIN' %}
                <a href="/home/delete/{{ post['id'] }}">
                    <button class="delete-post-button" name="delete_post_button" type="submit">Delete</button>
                </a>
            {% endif %}
            </article>
        {% endfor %}
    </div>
    <div class="col-md-4">
        <div class="content-section">
            <h3>Welcome {{ user }}</h3>
            <p class='text-muted'>
                Attention!
                <br/>
                We do not have strong security so please do not attack this site
            </p>
        </div>
    </div>
    {% if session['logged_in'] %}
        <form action="{{ url_for('home.home') }}" method="post">
            Add a new post: <br>
            <input class="post-title" name="post_title" type="text" placeholder="Title"><br>
            <textarea class="post-content" name="post_content" placeholder="Write something here"></textarea><br>
            <button type="submit">Add</button>
        </form>
    {% endif %}
    </div>
{% endblock content%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">

    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Home</title>
    {%  endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container col-md-12">
            <div class="col-md-9">
              <a class="navbar-brand mr-4" href="/">Crack me!</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user %}
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                {% endif %}
                <a class="nav-item nav-link" href="/about">About</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{%  extends "layout.html" %}
{% block content %}
    <div class="content-section col-md-8 ">
        <h3>Login</h3>
        <br/>
        <form action="{{ url_for('login.login') }}" method="post">
            <div class="msg">{{ msg }}</div>
            <input id="username" name="username" type="text" placeholder="Enter Your Username" class="textbox"/></br></br>
            <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br></br>
            <input type="submit" class="btn-outline-dark" value="Sign In">
        </form>
    </div>
    <div class="border-top pt-3 col-md-8">
        <small class="text-muted">
            Don't have an account? <a class="ml-2" href="{{ url_for('register.register') }}">Sign Up</a>
        </small>
    </div>
{% endblock content %}

templates/register.html
{%  extends "layout.html" %}
{% block content %}
     <div class="content-section col-md-8 ">
        <h3>Register</h3>
        <br/>
        <form action="{{ url_for('register.register') }}" method="post">
            <div class="msg">{{ msg }}</div>
            <input id="username" name="username" type="text" placeholder="Enter Your Username" class="textbox"/></br></br>
            <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br>
            <input id="email" name="email" type="text" placeholder="Enter Your Email ID" class="textbox"/></br></br>
            <input type="submit" class="btn-outline-dark" value="Sign Up">
        </form>
    </div>
    <div class="border-top pt-3 col-md-8">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('register.register') }}">Sign In here</a>
        </small>
    </div>
{% endblock content %}